// Realistic mock data for GymBud MVP

export const WORKOUT_TYPES = [
  'Push/Pull/Legs',
  'Upper/Lower',
  'Full Body',
  'Bro Split',
  'Strength Training',
  'Powerlifting',
  'CrossFit Style',
  'Bodybuilding',
  'Calisthenics',
  'HIIT',
];

export const GYMS = [
  { id: 'g1', name: 'Anytime Fitness - Eagle Rd', city: 'Boise' },
  { id: 'g2', name: 'YMCA Downtown', city: 'Boise' },
  { id: 'g3', name: 'Club Apple Fitness', city: 'Meridian' },
  { id: 'g4', name: 'Crunch Fitness - Overland', city: 'Boise' },
  { id: 'g5', name: 'Gold\'s Gym', city: 'Nampa' },
  { id: 'g6', name: 'Idaho Athletic Club', city: 'Eagle' },
];

export const MOCK_HOSTS = [
  {
    id: 'h1',
    name: 'Marcus Johnson',
    age: 27,
    avatar: null,
    initials: 'MJ',
    bio: 'Been lifting consistently for 6 years. I run a PPL split and take it seriously but keep it fun. Looking for someone who actually wants to put in work.',
    workoutType: 'Push/Pull/Legs',
    gym: GYMS[0],
    experience: '6 years',
    schedule: [
      { day: 'Monday', time: '6:00 AM', focus: 'Push (Chest/Shoulders/Triceps)' },
      { day: 'Tuesday', time: '6:00 AM', focus: 'Pull (Back/Biceps)' },
      { day: 'Wednesday', time: '6:00 AM', focus: 'Legs' },
      { day: 'Thursday', time: 'Rest', focus: null },
      { day: 'Friday', time: '6:00 AM', focus: 'Push (Chest/Shoulders/Triceps)' },
      { day: 'Saturday', time: '8:00 AM', focus: 'Pull (Back/Biceps)' },
      { day: 'Sunday', time: 'Rest', focus: null },
    ],
    pricePerSession: 15,
    weeklyPrice: 50,
    rating: 4.8,
    reviewCount: 23,
    verified: true,
    tags: ['Early Bird', 'Serious', 'Consistent'],
    joinedDate: '2024-08-15',
    sessionsHosted: 156,
  },
  {
    id: 'h2',
    name: 'Sarah Kim',
    age: 24,
    avatar: null,
    initials: 'SK',
    bio: 'Competed in my first bikini comp last year. I train 5x a week with a body building split. Chill vibes, loud music, good pump.',
    workoutType: 'Bodybuilding',
    gym: GYMS[3],
    experience: '4 years',
    schedule: [
      { day: 'Monday', time: '5:30 PM', focus: 'Glutes & Hamstrings' },
      { day: 'Tuesday', time: '5:30 PM', focus: 'Shoulders & Arms' },
      { day: 'Wednesday', time: '5:30 PM', focus: 'Back' },
      { day: 'Thursday', time: 'Rest', focus: null },
      { day: 'Friday', time: '5:30 PM', focus: 'Quads & Calves' },
      { day: 'Saturday', time: '10:00 AM', focus: 'Chest & Arms' },
      { day: 'Sunday', time: 'Rest', focus: null },
    ],
    pricePerSession: 20,
    weeklyPrice: 70,
    rating: 4.9,
    reviewCount: 41,
    verified: true,
    tags: ['Competitor', 'Evening', 'Good Music'],
    joinedDate: '2024-06-01',
    sessionsHosted: 312,
  },
  {
    id: 'h3',
    name: 'Derek Okonkwo',
    age: 31,
    avatar: null,
    initials: 'DO',
    bio: 'Powerlifter turned general strength. I keep it simple — big compound lifts, progressive overload, no BS. If you want fancy stuff, I\'m not your guy.',
    workoutType: 'Strength Training',
    gym: GYMS[1],
    experience: '9 years',
    schedule: [
      { day: 'Monday', time: '7:00 AM', focus: 'Squat Day' },
      { day: 'Tuesday', time: 'Rest', focus: null },
      { day: 'Wednesday', time: '7:00 AM', focus: 'Bench Day' },
      { day: 'Thursday', time: 'Rest', focus: null },
      { day: 'Friday', time: '7:00 AM', focus: 'Deadlift Day' },
      { day: 'Saturday', time: '9:00 AM', focus: 'Accessories' },
      { day: 'Sunday', time: 'Rest', focus: null },
    ],
    pricePerSession: 20,
    weeklyPrice: 60,
    rating: 4.7,
    reviewCount: 18,
    verified: true,
    tags: ['Strength', 'No BS', 'Compound Lifts'],
    joinedDate: '2024-11-10',
    sessionsHosted: 89,
  },
  {
    id: 'h4',
    name: 'Priya Mehta',
    age: 26,
    avatar: null,
    initials: 'PM',
    bio: 'Full body training 4x a week. I keep sessions under an hour and always superset. Great for people who are busy but want real results.',
    workoutType: 'Full Body',
    gym: GYMS[2],
    experience: '3 years',
    schedule: [
      { day: 'Monday', time: '12:00 PM', focus: 'Full Body A' },
      { day: 'Tuesday', time: 'Rest', focus: null },
      { day: 'Wednesday', time: '12:00 PM', focus: 'Full Body B' },
      { day: 'Thursday', time: 'Rest', focus: null },
      { day: 'Friday', time: '12:00 PM', focus: 'Full Body A' },
      { day: 'Saturday', time: '12:00 PM', focus: 'Full Body B' },
      { day: 'Sunday', time: 'Rest', focus: null },
    ],
    pricePerSession: 12,
    weeklyPrice: 40,
    rating: 4.6,
    reviewCount: 15,
    verified: false,
    tags: ['Efficient', 'Lunch Break', 'Supersets'],
    joinedDate: '2025-01-20',
    sessionsHosted: 45,
  },
  {
    id: 'h5',
    name: 'Jake Torres',
    age: 23,
    avatar: null,
    initials: 'JT',
    bio: 'Classic bro split because it works. I hit each muscle once a week hard. If you like high volume and a good pump this is your spot.',
    workoutType: 'Bro Split',
    gym: GYMS[0],
    experience: '5 years',
    schedule: [
      { day: 'Monday', time: '4:00 PM', focus: 'Chest' },
      { day: 'Tuesday', time: '4:00 PM', focus: 'Back' },
      { day: 'Wednesday', time: '4:00 PM', focus: 'Shoulders' },
      { day: 'Thursday', time: '4:00 PM', focus: 'Arms' },
      { day: 'Friday', time: '4:00 PM', focus: 'Legs' },
      { day: 'Saturday', time: 'Rest', focus: null },
      { day: 'Sunday', time: 'Rest', focus: null },
    ],
    pricePerSession: 10,
    weeklyPrice: 35,
    rating: 4.5,
    reviewCount: 32,
    verified: true,
    tags: ['Afternoon', 'High Volume', 'Good Pump'],
    joinedDate: '2024-09-05',
    sessionsHosted: 201,
  },
  {
    id: 'h6',
    name: 'Ava Rodriguez',
    age: 29,
    avatar: null,
    initials: 'AR',
    bio: 'Upper/Lower split, 4 days a week. I focus on progressive overload and tracking everything. I\'ll show you how to actually log your lifts.',
    workoutType: 'Upper/Lower',
    gym: GYMS[5],
    experience: '7 years',
    schedule: [
      { day: 'Monday', time: '6:30 AM', focus: 'Upper Body' },
      { day: 'Tuesday', time: '6:30 AM', focus: 'Lower Body' },
      { day: 'Wednesday', time: 'Rest', focus: null },
      { day: 'Thursday', time: '6:30 AM', focus: 'Upper Body' },
      { day: 'Friday', time: '6:30 AM', focus: 'Lower Body' },
      { day: 'Saturday', time: 'Rest', focus: null },
      { day: 'Sunday', time: 'Rest', focus: null },
    ],
    pricePerSession: 18,
    weeklyPrice: 55,
    rating: 4.9,
    reviewCount: 57,
    verified: true,
    tags: ['Data Driven', 'Early Bird', 'Progressive Overload'],
    joinedDate: '2024-04-12',
    sessionsHosted: 420,
  },
];

export const MOCK_REVIEWS = {
  h1: [
    { id: 'r1', author: 'Tyler B.', rating: 5, text: 'Marcus is the real deal. First day he showed me proper bench form and I felt it way more. Great energy.', date: '2025-03-10' },
    { id: 'r2', author: 'Amir K.', rating: 5, text: 'Been going with him for 3 weeks now. Already seeing progress. Feels like working out with a friend not a trainer.', date: '2025-03-05' },
    { id: 'r3', author: 'Jenny L.', rating: 4, text: 'Good workouts. He goes early though so you gotta commit to that 6am life.', date: '2025-02-28' },
  ],
  h2: [
    { id: 'r4', author: 'Keisha M.', rating: 5, text: 'Sarah is amazing!! Her workouts are so well structured and she always has a plan. Plus the music is fire.', date: '2025-03-12' },
    { id: 'r5', author: 'Lisa T.', rating: 5, text: 'Finally found someone who takes it as seriously as me. We push each other. Best investment I\'ve made.', date: '2025-03-08' },
    { id: 'r6', author: 'Dee P.', rating: 5, text: 'I was nervous joining a stranger but Sarah made it feel so natural. Like we\'d been gym buddies for years.', date: '2025-03-01' },
  ],
  h3: [
    { id: 'r7', author: 'Kellen S.', rating: 5, text: 'If you want strength, this is your guy. My squat went up 30lbs in a month just following his programming.', date: '2025-03-11' },
    { id: 'r8', author: 'Nate R.', rating: 4, text: 'Intense but effective. Not for beginners who want hand-holding. You gotta be ready to work.', date: '2025-02-20' },
  ],
  h5: [
    { id: 'r9', author: 'Chris D.', rating: 5, text: 'Jake is super chill and knows his stuff. The pump is always insane. Really affordable too.', date: '2025-03-09' },
    { id: 'r10', author: 'Matt W.', rating: 4, text: 'Good workouts, fun to train with. Only thing is he can run late sometimes.', date: '2025-02-25' },
  ],
  h6: [
    { id: 'r11', author: 'Rachel F.', rating: 5, text: 'Ava taught me how to actually track my lifts and progress. Game changer. My strength has gone up consistently.', date: '2025-03-13' },
    { id: 'r12', author: 'Sam J.', rating: 5, text: 'Most organized workout partner I\'ve ever had. She has everything planned out and we never waste time.', date: '2025-03-06' },
    { id: 'r13', author: 'Tina M.', rating: 5, text: 'Worth every penny. I\'ve tried 3 personal trainers and Ava\'s approach actually works because you feel like equals.', date: '2025-02-28' },
  ],
};

export const MOCK_BOOKINGS = [
  {
    id: 'b1',
    hostId: 'h1',
    date: '2025-03-26',
    day: 'Wednesday',
    time: '6:00 AM',
    focus: 'Legs',
    status: 'confirmed',
  },
  {
    id: 'b2',
    hostId: 'h1',
    date: '2025-03-28',
    day: 'Friday',
    time: '6:00 AM',
    focus: 'Push (Chest/Shoulders/Triceps)',
    status: 'confirmed',
  },
  {
    id: 'b3',
    hostId: 'h2',
    date: '2025-03-24',
    day: 'Monday',
    time: '5:30 PM',
    focus: 'Glutes & Hamstrings',
    status: 'completed',
  },
];
